const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "./images/item-1.jpeg",
    desc: `Per Serving: 219 calories; protein 7.2g; carbohydrates 30.7g; fat 7.4g; cholesterol 63.3mg; sodium 515.5mg.`,
  },
  {
    id: 2,
    title: "diner double",
    category: "lunch",
    price: 13.99,
    img: "./images/item-2.jpeg",
    desc: `Per Serving: 967 calories; protein 56.1g; carbohydrates 35.2g; fat 67.5g; cholesterol 365.6mg; sodium 1854.8mg. `,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "./images/item-3.jpeg",
    desc: `Per Serving: 272 calories; protein 5g; carbohydrates 45.7g; fat 8.7g; cholesterol 33.9mg; sodium 78.7mg.`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "./images/item-4.jpeg",
    desc: `Per Serving: 471 calories; protein 18.1g; carbohydrates 29.6g; fat 31.5g; cholesterol 248mg; sodium 995.8mg.`,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "./images/item-5.jpeg",
    desc: `Per Serving: 875 calories; protein 52g; carbohydrates 40.1g; fat 55.2g; cholesterol 327.7mg; sodium 2024.4mg.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "./images/item-6.jpeg",
    desc: `Per Serving: 557 calories; protein 8.7g; carbohydrates 75.8g; fat 24.3g; cholesterol 67.5mg; sodium 196.4mg.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "./images/item-7.jpeg",
    desc: `Per Serving: 794 calories; protein 42g; carbohydrates 36.6g; fat 60.4g; cholesterol 373.6mg; sodium 2331.6mg.`,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "./images/item-8.jpeg",
    desc: `Per Serving: 257 calories; protein 7.8g; carbohydrates 29.8g; fat 12.1g; cholesterol 74.7mg; sodium 187.8mg.`,
  },
  {
    id: 9,
    title: "Big bad burger",
    category: "lunch",
    price: 16.99,
    img: "./images/item-9.jpeg",
    desc: `Per Serving: 794 calories; protein 42g; carbohydrates 36.6g; fat 60.4g; cholesterol 373.6mg; sodium 2331.6mg.`,
  },
  {
    id: 10,
    title: "riverwood's main course",
    category: "unusual item",
    price: 720.99,
    img: "./images/skyrim-meal.jpg",
    desc: `Per Serving: 5999 calories; protein 420g; carbohydrates 69.6g; fat 13.37g; cholesterol 111.6mg; sodium 3.6mg.`,
  },
];
export default menu;
